version: "3"
services:
    nginx:
        restart: on-failure
        build: ./nginx
        depends_on:
            - api
        ports:
            - "80:80"
        command: /usr/sbin/nginx
    api:
        restart: on-failure
        build: ./api
        depends_on:
            - postgresql
        expose:
            - "8000"
            - "8001"
        environment:
            - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
            - POSTGRES_DB_USER=${POSTGRES_DB_USER}
            - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - ADMIN_USER=${ADMIN_USER}
            - ADMIN_USER_EMAIL=${ADMIN_USER_EMAIL}
            - ADMIN_USER_PASSWORD=${ADMIN_USER_PASSWORD}
        command: "/opt/bin/build.sh"
    postgresql:
        restart: on-failure
        build: ./postgres
        expose:
            - "5432"
        environment:
            - POSTGRES_DB=${POSTGRES_DB_NAME}
            - POSTGRES_USER=${POSTGRES_DB_USER}
            - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
