--- # install docker-compose
- name: "download docker-compose binary"
  get_url: 
    url : "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: "/usr/local/bin/docker-compose"
    mode: "0755"
