--- # Install and configure the sshd service
- name: "Install sshd"
  apt:
    name: "openssh-server"
    state: "present"
    update_cache: true

- name: "Replace /etc/ssh/sshd_config"
  file:
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: "root"
    group: "root"
    mode: "0644"

